### ISSUE TITLE
Add modal (pop up) window http://www.pilgrimages.com/eastern/

### ISSUE THREAD

**Issue by Andrey1901** [ronen206tours/Andrew#10]
Eight Lines to show on Website:

Usama has studied Biblical Archaeology and History at the Stadium Biblicum Franciscanum  (SBF) in Jerusalem, followed by a B.A. Degree at Empire state College, and a Master of Science Degree in Management from Cardinal Stritch University in Milwaukee (specializing in Christian non-profit organizations). In addition to being an active member of the Catholic Church in Jerusalem, and working as a full time guide, for the past several years – he has been working on his PhD Thesis titled: “Strengthening the Christian Presence in the Holy Land through Strategic Planning”. He has guided many Catholic leaders, including Dr. Scott Hahn, His Grace Archbishop Richard Smith, Archbishop of Edmonton (and past President of the Canadian Conference of Catholic Bishops.)

 

Instead of Button reading “More About Usama”, have it read “Usama’s Full Bio – Click Here”

 

Full Biography:

For the past several years, I have been working on a comprehensive analysis through my Ph.D Program on how to help the Christian Community in the Holy Land, which I am part of. This unique community has been in existence for more than 2000 years, and the first people Jesus called the "Living Stones" and "Salt of the Earth". The analysis research focuses on strengthening the Christian presence in the Holy Land through a strategic program. It is also concentrated on maintaining and preserving the Christian identity, and the Christian communities and congregations in Palestine and Israel. The research presented here applies a SWOT analysis to the history, the current reality of the Christian presence in the Holy Land, and the challenges that influence its future. The benefit of using this approach allows for a concrete analysis of the problems that face the Christian community from the Palestinian-Israel conflict, economic instability, social problems, and the Christian cultural predicament, identified from the literature. Having done this research, it gave me the opportunity to increase my understanding of the needs of the Palestinian Christian community needs in different perception. Affecting their daily lives in addition to new methods to reduce the cap between the three major religions, in order to have better understanding that help bring peace and justice.

 

Working as a Tour Guide in the Holy Land has given me the opportunity to be connected to the Christians, Catholic imparticular, coming from all over the world. I have used my work - not just to bring the Bible alive and to give them the opportunity to experience the fifth gospel, but to introduce educational awareness, information about the living stones, and the difficulties they are facing to preserve the Christian presence in the Holy Land. Besides working as a Tour Guide, I am working towards establishing a Christian Research and Awareness House (“Mission Four Corners”) that provides concrete researched and awareness information to local and worldwide Christians concerning the defacement of the Christians and Christianity presence in the Holy Land. Mission Four Corners, is a formulation of contextual Christian history, presence and future research documentation that attempts to address the problems facing the Holy Land Christians emphasizing on their real life and practice that has often not been obvious or explained either to local and international Christians.

 

EDUCATION:

University of Wales: Trinity Saint David, Lampeter - U.K. (Doctorate of Philosophy, School of Theology, Religious Studies & Islamic Studies. – “Thesis Title: Strengthen the Christian Presence in the Holy Land through Strategic Planning Programs)

Israeli School of Tourism - Jerusalem, Israel (Tour Guide Coordinator)

Cardinal Stritch University - Milwaukee, U.S.A. (Master of Science in Management. Area of Concentration - Non-Profit Organizations)

SUNY Empire State College - Jerusalem, Israel. (Bachelor of Arts - International Relations)

Studium Biblicum Franciscanum – Jerusalem (Israel Biblical Information & Archeology)

**Comment by Andrey1901** [comment]
http://www.pilgrimages.com/eastern/index-33-modal.htm - the page is ready

**Comment by ronen206tours** [comment]
TY
