### ISSUE TITLE
volume control and size control for youtube video

### ISSUE THREAD

**Issue by ronenreinheimer** [ronen206tours/Andrew#16]
http://www.206tours.com/scotthahn

please check if it possible to add a volume control / half size control to this video

**Comment by Andrey1901** [comment]
Hi @ronenreinheimer as far as I can there are no options to add the volume/size control for the video frame such small size. It's the specifics of the YouTube player. 

Alternatively, you can think of another place to put the video with the larger size and you'll have all controls then.

Best
Andrew
