### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by ronenreinheimer** [ronen206tours/Andrew#17]
https://www.wayfair.com/v/about/meet_the_team

we need a page like this please

add the text from this page:
http://www.206tours.com/aboutus

keep a slot for the top banner, but comment out the code for now - so it is hidden

**Comment by Andrey1901** [comment]
Hi @ronenreinheimer the page is ready for review here - https://www.206tours.com/aboutus/index33-v2.htm
