### ISSUE TITLE
www.pilgrimages.com/weible  add multiple javascript modals

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#25]
http://www.pilgrimages.com/weible 

email sent 8/1/2018

![image](https://user-images.githubusercontent.com/38356174/43544779-fb34ead2-95a1-11e8-8fc7-07c189445ee2.png)

**Comment by Andrey1901** [comment]
http://www.pilgrimages.com/weible/index33-modal.htm - please review and let me know if it's done. Thanks!
