### ISSUE TITLE
FW: wont let me put an order through (sandy)

### ISSUE THREAD

**Issue by ronenreinheimer** [ronen206tours/Andrew#29]
![image](https://user-images.githubusercontent.com/10079829/44162866-9d9ed600-a08f-11e8-8740-de0bff24cc88.png)

**Comment by Andrey1901** [comment]
![image](https://user-images.githubusercontent.com/7030096/44312579-5607a980-a403-11e8-9dfe-8b44c8c2564c.png)
Pending for the reply from Brad.

**Comment by Andrey1901** [comment]
Hi @ronenreinheimer this was discussed in email thread "wont let me put an order through (sandy) #3652"

Here's the screenshot of the last email in it

![image](https://user-images.githubusercontent.com/7030096/44594622-676bff80-a7cf-11e8-9d45-340e97b8776e.png)
