### ISSUE TITLE
code overlap issue - VIP client

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#32]
Andrew,

Can you please look into this:
http://pilgrimages.com/matthewleonard

![image](https://user-images.githubusercontent.com/38356174/44219101-347b9900-a149-11e8-9dcb-9b1074ef47e7.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours should be fine now. Please check. 

Thanks! 
Andrew
