### ISSUE TITLE
RE: URGENT - pilgrimages.com ...booking section -- does not work -- it's worse than what it was before

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#33]
![image](https://user-images.githubusercontent.com/38356174/44223087-98f02580-a154-11e8-8df1-03a9a0236b0a.png)

Hi Brad,

Can you please covert these additional tours:
http://www.pilgrimages.com/eastern
http://www.pilgrimages.com/angelconnection
http://www.pilgrimages.com/srbettwy
http://www.pilgrimages.com/frtoohey
http://www.pilgrimages.com/frarturo
http://www.pilgrimages.com/frdaigle
http://www.pilgrimages.com/franthonyco
http://www.pilgrimages.com/clevelandpriests
http://www.pilgrimages.com/keas

Andrew,
Please check the code on these:
http://www.pilgrimages.com/msgrjameson
http://www.pilgrimages.com/kosco
http://www.pilgrimages.com/frbutler
http://www.pilgrimages.com/keas/mexico

**Comment by Andrey1901** [comment]
Hi @ronen206tours , I've replied already on this in my email. Please check my reply on the screenshot below
![image](https://user-images.githubusercontent.com/7030096/44229407-a59a6b00-a1a0-11e8-879f-1feef40990d6.png)
