### ISSUE TITLE
Dates prices is broken in the mobile view of all oberammergau pages (chris)

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#34]
http://www.206tours.com/oberammergau/spain/37

![image](https://user-images.githubusercontent.com/38356174/44230231-939cd600-a168-11e8-83b6-cbf10559ef02.png)

**Comment by Andrey1901** [comment]
Hi Ronen,

You have the wrong code structure here, fixed now. Please check. 
http://www.206tours.com/oberammergau/spain/37/

Thanks
Andrew
