### ISSUE TITLE
please adjust image height

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#35]
http://www.pilgrimages.com/university-of-steubenville

![image](https://user-images.githubusercontent.com/38356174/44268724-5ab04000-a200-11e8-8502-24b32dc115c3.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, the file updated, you may check and downloaded it then

http://www.pilgrimages.com/university-of-steubenville/
