### ISSUE TITLE
https://www.206tours.com/brochure

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#39]
brochure is not showing up in https

works:
http://www.206tours.com/brochure

doesnt work:
https://www.206tours.com/brochure

![image](https://user-images.githubusercontent.com/38356174/44354039-c3085700-a476-11e8-9334-2a8ed642d5b1.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, fixed this
