### ISSUE TITLE
Redesign Booking Section

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#4]
http://www.206tours.com/ronen/business-class-upgrade

i asked owner to select which iphone version she likes better (i will update project when she replies)

**can you make this section, scroll down as user scrolls to view more travel dates?
![image](https://user-images.githubusercontent.com/38356174/38747522-24987bf8-3f19-11e8-8d0c-91c8d56f37bf.png)

*Please Match Layout as closely as possible

thank you!

**Comment by ronen206tours** [comment]
![image](https://user-images.githubusercontent.com/38356174/38747744-d542df8e-3f19-11e8-8c99-70df9b8f5019.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, could you please check the screenshot and let me know if we moving in the right direction: https://prnt.sc/j8v2h7

Thanks in advance!
