### ISSUE TITLE
Booking Section - dropdown menu scrolls up issue

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#44]
when the booking section is low in the page, the dropdown menu goes up and it doesn't work well.

example:
www.pilgrimages.com/brammer

please review:
![image](https://user-images.githubusercontent.com/38356174/44424864-51083e80-a558-11e8-85eb-d4e4c619ac6f.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, 

It looks like this issues was resolved in some other ticket and we can close this one:
![image](https://user-images.githubusercontent.com/7030096/62241281-8a406400-b3e1-11e9-960c-f160bb7c2073.png)
