### ISSUE TITLE
adjust top sticky for booking section

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#47]
it is scrolling for an extended length past the booking section (especially with specials)

sample:
http://www.pilgrimages.com/frconnolly

![image](https://user-images.githubusercontent.com/38356174/44474354-75b7f100-a600-11e8-8a1b-6dcb2153afc2.png)

**Comment by ronen206tours** [comment]
pilgrimages.com/eastern/march
![image](https://user-images.githubusercontent.com/38356174/45705852-a2e8b800-bb48-11e8-8785-6cf32cf75412.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, this is ready on the staging and will go live with the updates for the booking section next week.

**Comment by Andrey1901** [comment]
Hi @ronen206tours, it was fixed alongside with the deployment of the updated booking section
