### ISSUE TITLE
Formatting Problem when half-screen 

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#48]
![image](https://user-images.githubusercontent.com/38356174/44475298-a6008f00-a602-11e8-94ce-9fc1288e8aa5.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours - fixed, please check.

![image](https://user-images.githubusercontent.com/7030096/46369839-bd647a80-c68c-11e8-9fb1-0622b18eb528.png)


Best
Andrew

**Comment by ronen206tours** [comment]
TY!
