### ISSUE TITLE
WEB: Travel Documents Website (convert to new format)

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#49]
www.206tours.com/documents/index.htm 

![image](https://user-images.githubusercontent.com/38356174/44550833-61a0ec00-a6f3-11e8-875a-d9a82b1f8393.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, please check
http://www.206tours.com/documents/index33.htm

Best
Andrew

**Comment by ronen206tours** [comment]
TY
