### ISSUE TITLE
Complete Pilgrimage Directory

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#51]
http://www.206tours.com/pilgrimages/index34.htm

1. can you please make this page narrower
2. please allocate more space for the destinations tab (so it doesn't wrap into additional lines)

makes sense?

![image](https://user-images.githubusercontent.com/38356174/44598391-e433b500-a7a0-11e8-9f3b-0fca21b3a9fa.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, updated here - http://www.206tours.com/pilgrimages/index33.htm

Thanks 
Andrew

**Comment by ronen206tours** [comment]
please check code for IE browser - as per VP
![image](https://user-images.githubusercontent.com/38356174/45117540-eb08e300-b123-11e8-86c8-a58c31b0d3d7.png)

**Comment by ronen206tours** [comment]
also please make the links blue

**Comment by Andrey1901** [comment]
Hi @ronen206tours updates were made, please check.

Best
Andrew

**Comment by ronen206tours** [comment]
TY
