### ISSUE TITLE
please adjust space

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#53]
http://www.pilgrimages.com/eastern

*not sure why this space occured

![image](https://user-images.githubusercontent.com/38356174/44666053-85ab4880-a9e5-11e8-9317-744c55ab86e5.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, fixes were made for pages: 

- http://www.pilgrimages.com/eastern/march/
- http://www.pilgrimages.com/eastern/ 

Thanks
Andrew

**Comment by ronen206tours** [comment]
TY!
