### ISSUE TITLE
Customize you trip

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#54]
Can you please build me some responsive custom HTML for this:

http://www.pilgrimages.com/eastern/holyland

![image](https://user-images.githubusercontent.com/38356174/44671893-bf378000-a9f4-11e8-9a3d-9daa3ade6552.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours. the basic layout of this section is available on this page:
https://www.206tours.com/front_development/dev/GH54/#


Could you please share some "live" content so we can place there and that it looks good

**Comment by ronen206tours** [comment]
TY
