### ISSUE TITLE
Two column information section

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#57]
on this page:
http://www.206tours.com/causes/index34.htm

I need this:

![image](https://user-images.githubusercontent.com/38356174/44737340-b6f84700-aabf-11e8-9968-0bd2a60062fd.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, updates are ready - http://www.206tours.com/causes/index33.htm

Thanks
Andrew

**Comment by ronen206tours** [comment]
TY!
