### ISSUE TITLE
Add Pre Tour Section

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#59]
http://www.206tours.com/divinemercy/index35.htm

sample:
http://pilgrimages.com/frseeman

please add it here:
![image](https://user-images.githubusercontent.com/38356174/44748895-f2eed480-aade-11e8-90b3-639bb9552cdf.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, I've added sections here - http://www.206tours.com/divinemercy/index33.htm

Thanks 
Andrew

**Comment by ronen206tours** [comment]
TY
