### ISSUE TITLE
Spiritual Leader & Logo inserts splash page

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#60]
can you add two location where we can upload 2 images

sample:
www.pilgrimages.com/msgrswiader

![image](https://user-images.githubusercontent.com/38356174/44799357-b922da00-ab81-11e8-9f21-b68154dc9b57.png)

![image](https://user-images.githubusercontent.com/38356174/44799301-97c1ee00-ab81-11e8-849b-e0794903c097.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours the layout is ready, you just need to add the new image on the left
https://github.com/ronen206tours/Andrew/issues/49

Best
Andrew

**Comment by ronen206tours** [comment]
TY
