### ISSUE TITLE
Please fix overlap

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#63]
http://www.206tours.com/rlc/index34.htm

![image](https://user-images.githubusercontent.com/38356174/44870603-a500da80-ac5e-11e8-8b51-747c7cd28f1f.png)

**Comment by Andrey1901** [comment]
Hi Ronen, 

This one is ready, please check.
http://www.206tours.com/rlc/index33.htm

Best
Andrew

**Comment by ronen206tours** [comment]
TY
