### ISSUE TITLE
side by side youtube embeded videos

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#65]
name it index38.htm

http://www.206tours.com/rlc

![image](https://user-images.githubusercontent.com/38356174/44918449-f796d100-ad08-11e8-8a0c-74abd0caf7ed.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours, this one is ready https://www.206tours.com/front_development/dev/chrisstefanick.html#
