### ISSUE TITLE
Please make this section responsive for tablet / iphone

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#67]
Andrew,

Please make this section responsive for tablet / iphone.

Super urgent.

Thank you.

www.206tours.com/jimcaviezel

![image](https://user-images.githubusercontent.com/38356174/45273774-2720a880-b482-11e8-8af1-448d8d4294b1.png)

**Comment by ronen206tours** [comment]
![image](https://user-images.githubusercontent.com/38356174/45274561-0eb28d00-b486-11e8-8a2e-04788dd337b9.png)

**Comment by Andrey1901** [comment]
Hi @ronen206tours the update is ready 
http://www.206tours.com/jimcaviezel/

**Comment by ronen206tours** [comment]
thank you Andrew, i will have some edits soon
