### ISSUE TITLE
Proposal Directories for 206tours.com and pilgrimages.com - hidden from search engines and password protected

### ISSUE THREAD

**Issue by ronen206tours** [ronen206tours/Andrew#68]
Andrew,

please setup these directory:
www.206tours.com/proposal/
www.pilgrimages.com/proposal/

they will be PW protected and hidden from search engines

**Comment by Andrey1901** [comment]
Hi @ronen206tours this one is ready

**Comment by ronen206tours** [comment]
login: **saint**
pw: **francis**
